apiVersion: v1
kind: Pod
metadata:
 name: vol-test
 labels:
   app: vol-test
spec:
 containers:
 - image: docker.io/rubegolberg22/critest:latest
   command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
   name: vol-test
   imagePullPolicy: Always
 restartPolicy: Never
 terminationGracePeriodSeconds: 3
